const categories: Record<string, { word: string; hint: string }[]> = {
  "Animals": [
    { word: "Elephant", hint: "Big" },
    { word: "Giraffe", hint: "Tall" },
    { word: "Penguin", hint: "Cold" },
    { word: "Dolphin", hint: "Ocean" },
    { word: "Kangaroo", hint: "Hops" },
    { word: "Octopus", hint: "Underwater" },
    { word: "Flamingo", hint: "Pink" },
    { word: "Cheetah", hint: "Fast" },
    { word: "Panda", hint: "Black white" },
    { word: "Chameleon", hint: "Changes" },
    { word: "Peacock", hint: "Beautiful" },
    { word: "Hamster", hint: "Small" },
    { word: "Jaguar", hint: "Wild" },
    { word: "Koala", hint: "Trees" },
    { word: "Lobster", hint: "Sea" },
    { word: "Chimpanzee", hint: "Smart" },
    { word: "Walrus", hint: "Cold" },
    { word: "Parrot", hint: "Talks" },
    { word: "Scorpion", hint: "Desert" },
    { word: "Toucan", hint: "Tropical" },
    { word: "Hedgehog", hint: "Spikes" },
    { word: "Platypus", hint: "Unusual" },
    { word: "Raccoon", hint: "Mask" },
    { word: "Seahorse", hint: "Ocean" },
    { word: "Sloth", hint: "Slow" },
    { word: "Meerkat", hint: "Desert" },
    { word: "Narwhal", hint: "Arctic" },
    { word: "Otter", hint: "River" },
    { word: "Puffin", hint: "Sea" },
    { word: "Armadillo", hint: "Hard" },
    { word: "Buffalo", hint: "Horns" },
    { word: "Camel", hint: "Desert" },
    { word: "Dragonfly", hint: "Flying" },
    { word: "Eagle", hint: "Bird" },
    { word: "Ferret", hint: "Small" },
    { word: "Gecko", hint: "Lizard" },
    { word: "Heron", hint: "Bird" },
    { word: "Iguana", hint: "Lizard" },
    { word: "Lemur", hint: "Madagascar" },
    { word: "Moose", hint: "Antlers" },
    { word: "Newt", hint: "Amphibian" },
    { word: "Ostrich", hint: "Bird" },
    { word: "Pelican", hint: "Beak" },
    { word: "Quail", hint: "Bird" },
    { word: "Rhinoceros", hint: "Horn" },
    { word: "Starfish", hint: "Ocean" },
    { word: "Tiger", hint: "Stripes" },
    { word: "Vulture", hint: "Bird" },
    { word: "Yak", hint: "Hairy" },
    { word: "Wolverine", hint: "Claws" }
  ],
  "Food & Drink": [
    { word: "Pizza", hint: "Round" },
    { word: "Sushi", hint: "Rolled" },
    { word: "Tacos", hint: "Folded" },
    { word: "Pasta", hint: "Italian" },
    { word: "Burger", hint: "Round" },
    { word: "Croissant", hint: "Breakfast" },
    { word: "Paella", hint: "Spanish" },
    { word: "Ramen", hint: "Soup" },
    { word: "Dim Sum", hint: "Steamed" },
    { word: "Falafel", hint: "Fried" },
    { word: "Brownie", hint: "Sweet" },
    { word: "Mango", hint: "Sweet" },
    { word: "Avocado", hint: "Green" },
    { word: "Bacon", hint: "Breakfast" },
    { word: "Cinnamon", hint: "Spicy" },
    { word: "Wasabi", hint: "Green" },
    { word: "Saffron", hint: "Yellow" },
    { word: "Kimchi", hint: "Spicy" },
    { word: "Mozzarella", hint: "Soft" },
    { word: "Gumbo", hint: "Soup" },
    { word: "Churro", hint: "Fried" },
    { word: "Baguette", hint: "Bread" },
    { word: "Cannoli", hint: "Sweet" },
    { word: "Hummus", hint: "Dip" },
    { word: "Matcha", hint: "Green" },
    { word: "Lasagna", hint: "Italian" },
    { word: "Bagel", hint: "Breakfast" },
    { word: "Kebab", hint: "Grilled" },
    { word: "Cupcake", hint: "Sweet" },
    { word: "Pancake", hint: "Breakfast" },
    { word: "Almond", hint: "Nut" },
    { word: "Chili", hint: "Spicy" },
    { word: "Durian", hint: "Smelly" },
    { word: "Eggplant", hint: "Purple" },
    { word: "Figs", hint: "Fruit" },
    { word: "Ginger", hint: "Spicy" },
    { word: "Honey", hint: "Sweet" },
    { word: "Ice Cream", hint: "Sweet" },
    { word: "Jalapeno", hint: "Spicy" },
    { word: "Kiwi", hint: "Green" },
    { word: "Lemon", hint: "Sour" },
    { word: "Nachos", hint: "Cheesy" },
    { word: "Olive", hint: "Salty" },
    { word: "Pineapple", hint: "Tropical" },
    { word: "Quinoa", hint: "Grain" },
    { word: "Raisin", hint: "Dried" },
    { word: "Truffle", hint: "Fancy" },
    { word: "Popcorn", hint: "Movies" },
    { word: "Waffles", hint: "Breakfast" },
    { word: "Salsa", hint: "Dance" }
  ],
  "Countries": [
    { word: "Japan", hint: "Island" },
    { word: "Brazil", hint: "Warm" },
    { word: "Iceland", hint: "Cold" },
    { word: "Egypt", hint: "Desert" },
    { word: "Thailand", hint: "Hot" },
    { word: "Peru", hint: "Mountains" },
    { word: "Norway", hint: "Cold" },
    { word: "Kenya", hint: "Warm" },
    { word: "Cuba", hint: "Island" },
    { word: "Nepal", hint: "Mountains" },
    { word: "Vietnam", hint: "Hot" },
    { word: "Greece", hint: "Island" },
    { word: "Morocco", hint: "Desert" },
    { word: "Chile", hint: "Long" },
    { word: "Finland", hint: "Cold" },
    { word: "Indonesia", hint: "Island" },
    { word: "Jamaica", hint: "Island" },
    { word: "Madagascar", hint: "Island" },
    { word: "Mongolia", hint: "Cold" },
    { word: "Portugal", hint: "Coast" },
    { word: "Scotland", hint: "Cold" },
    { word: "Sri Lanka", hint: "Island" },
    { word: "Tanzania", hint: "Warm" },
    { word: "Uruguay", hint: "Grasslands" },
    { word: "Cambodia", hint: "Hot" },
    { word: "Ethiopia", hint: "Dry" },
    { word: "Hungary", hint: "Middle" },
    { word: "Ireland", hint: "Island" },
    { word: "Myanmar", hint: "Hot" },
    { word: "Sweden", hint: "Cold" },
    { word: "Argentina", hint: "Warm" },
    { word: "Belgium", hint: "Small" },
    { word: "Canada", hint: "Cold" },
    { word: "Denmark", hint: "Small" },
    { word: "Ecuador", hint: "Warm" },
    { word: "France", hint: "Europe" },
    { word: "Georgia", hint: "Mountains" },
    { word: "Haiti", hint: "Island" },
    { word: "India", hint: "Warm" },
    { word: "Jordan", hint: "Desert" },
    { word: "Kuwait", hint: "Oil" },
    { word: "Laos", hint: "Landlocked" },
    { word: "Mexico", hint: "Spicy" },
    { word: "Nigeria", hint: "Warm" },
    { word: "Oman", hint: "Desert" },
    { word: "Poland", hint: "Cold" },
    { word: "Qatar", hint: "Desert" },
    { word: "Russia", hint: "Cold" },
    { word: "Turkey", hint: "Bridge" },
    { word: "Venezuela", hint: "Warm" }
  ],
  "Movies": [
    { word: "Titanic", hint: "Boat" },
    { word: "Avatar", hint: "Blue" },
    { word: "Jaws", hint: "Ocean" },
    { word: "Frozen", hint: "Snow" },
    { word: "Gladiator", hint: "Ancient" },
    { word: "Inception", hint: "Dreams" },
    { word: "Casablanca", hint: "Old" },
    { word: "Rocky", hint: "Fight" },
    { word: "Alien", hint: "Space" },
    { word: "Braveheart", hint: "Warrior" },
    { word: "Amelie", hint: "Paris" },
    { word: "Vertigo", hint: "Tall" },
    { word: "Jumanji", hint: "Jungle" },
    { word: "Ratatouille", hint: "Food" },
    { word: "Shrek", hint: "Green" },
    { word: "Memento", hint: "Memory" },
    { word: "Coco", hint: "Family" },
    { word: "Fargo", hint: "Snow" },
    { word: "Scream", hint: "Scary" },
    { word: "Twister", hint: "Storm" },
    { word: "Bambi", hint: "Forest" },
    { word: "Gremlins", hint: "Little" },
    { word: "Chocolat", hint: "Food" },
    { word: "Babe", hint: "Farm" },
    { word: "Signs", hint: "Space" },
    { word: "Prestige", hint: "Magic" },
    { word: "Crash", hint: "Cars" },
    { word: "Slumdog", hint: "India" },
    { word: "Up", hint: "Flying" },
    { word: "WALL-E", hint: "Robot" },
    { word: "Back to the Future", hint: "Time" },
    { word: "Citizen Kane", hint: "Classic" },
    { word: "E.T.", hint: "Alien" },
    { word: "Forrest Gump", hint: "Running" },
    { word: "Ghostbusters", hint: "Ghosts" },
    { word: "Home Alone", hint: "Christmas" },
    { word: "Interstellar", hint: "Space" },
    { word: "Jurassic Park", hint: "Dinosaurs" },
    { word: "King Kong", hint: "Monster" },
    { word: "La La Land", hint: "Musical" },
    { word: "Mad Max", hint: "Desert" },
    { word: "Notebook", hint: "Romance" },
    { word: "Onward", hint: "Magic" },
    { word: "Pulp Fiction", hint: "Crime" },
    { word: "Soul", hint: "Music" },
    { word: "X-Men", hint: "Heroes" },
    { word: "Zootopia", hint: "Animals" },
    { word: "Metropolis", hint: "City" },
    { word: "Blade Runner", hint: "Future" },
    { word: "Shutter Island", hint: "Mystery" }
  ],
  "Sports": [
    { word: "Soccer", hint: "Ball" },
    { word: "Basketball", hint: "Ball" },
    { word: "Tennis", hint: "Court" },
    { word: "Boxing", hint: "Fists" },
    { word: "Surfing", hint: "Water" },
    { word: "Cricket", hint: "Team" },
    { word: "Fencing", hint: "Swords" },
    { word: "Curling", hint: "Ice" },
    { word: "Karate", hint: "Kicking" },
    { word: "Rugby", hint: "Ball" },
    { word: "Badminton", hint: "Net" },
    { word: "Skiing", hint: "Snow" },
    { word: "Volleyball", hint: "Net" },
    { word: "Archery", hint: "Aim" },
    { word: "Cycling", hint: "Fast" },
    { word: "Snooker", hint: "Table" },
    { word: "Judo", hint: "Throwing" },
    { word: "Lacrosse", hint: "Team" },
    { word: "Rowing", hint: "Water" },
    { word: "Dodgeball", hint: "Ball" },
    { word: "Triathlon", hint: "Swimming" },
    { word: "Polo", hint: "Horses" },
    { word: "Bowling", hint: "Pins" },
    { word: "Parkour", hint: "Running" },
    { word: "Snowboarding", hint: "Snow" },
    { word: "Taekwondo", hint: "Kicking" },
    { word: "Handball", hint: "Ball" },
    { word: "Mountain", hint: "Climbing" },
    { word: "Kayaking", hint: "Water" },
    { word: "Bouldering", hint: "Climbing" },
    { word: "American Football", hint: "Ball" },
    { word: "Baseball", hint: "Bat" },
    { word: "Chess Boxing", hint: "Mixed" },
    { word: "Diving", hint: "Water" },
    { word: "Equestrian", hint: "Horses" },
    { word: "Frisbee", hint: "Throw" },
    { word: "Golf", hint: "Hole" },
    { word: "Hockey", hint: "Ice" },
    { word: "Ice Skating", hint: "Ice" },
    { word: "Javelin", hint: "Throw" },
    { word: "Kickboxing", hint: "Kicking" },
    { word: "Long Jump", hint: "Track" },
    { word: "Marathon", hint: "Running" },
    { word: "Netball", hint: "Team" },
    { word: "Paddleboarding", hint: "Water" },
    { word: "Rock Climbing", hint: "Climbing" },
    { word: "Squash", hint: "Racket" },
    { word: "Table Tennis", hint: "Racket" },
    { word: "Ultimate Frisbee", hint: "Team" },
    { word: "Weightlifting", hint: "Heavy" }
  ],
  "Hobbies": [
    { word: "Gardening", hint: "Plants" },
    { word: "Knitting", hint: "Yarn" },
    { word: "Origami", hint: "Paper" },
    { word: "Calligraphy", hint: "Writing" },
    { word: "Pottery", hint: "Clay" },
    { word: "Geocaching", hint: "Outside" },
    { word: "Scrapbook", hint: "Photos" },
    { word: "Birdwatch", hint: "Birds" },
    { word: "Astronomy", hint: "Stars" },
    { word: "Woodwork", hint: "Wood" },
    { word: "Sudoku", hint: "Numbers" },
    { word: "Chess", hint: "Board" },
    { word: "Photography", hint: "Photos" },
    { word: "Baking", hint: "Kitchen" },
    { word: "Camping", hint: "Outside" },
    { word: "Fishing", hint: "Water" },
    { word: "Yoga", hint: "Stretching" },
    { word: "Brewing", hint: "Kitchen" },
    { word: "Sewing", hint: "Fabric" },
    { word: "Drawing", hint: "Art" },
    { word: "Meditation", hint: "Quiet" },
    { word: "Tattoo", hint: "Ink" },
    { word: "Magic", hint: "Tricks" },
    { word: "Karaoke", hint: "Singing" },
    { word: "Collecting", hint: "Things" },
    { word: "Hiking", hint: "Outside" },
    { word: "Painting", hint: "Art" },
    { word: "Dancing", hint: "Music" },
    { word: "Running", hint: "Cardio" },
    { word: "Reading", hint: "Books" },
    { word: "Antiquing", hint: "Old" },
    { word: "Bonsai", hint: "Trees" },
    { word: "Coin Collecting", hint: "Coins" },
    { word: "Diorama", hint: "Miniature" },
    { word: "Embroidery", hint: "Needle" },
    { word: "Falconry", hint: "Birds" },
    { word: "Glassblowing", hint: "Hot" },
    { word: "Horseback", hint: "Animals" },
    { word: "Indie Games", hint: "Gaming" },
    { word: "Jewelry Making", hint: "Beads" },
    { word: "Kayaking", hint: "Water" },
    { word: "Lockpicking", hint: "Keys" },
    { word: "Metal Detecting", hint: "Metal" },
    { word: "Model Building", hint: "Miniature" },
    { word: "Needlepoint", hint: "Thread" },
    { word: "Podcasting", hint: "Audio" },
    { word: "Quilting", hint: "Fabric" },
    { word: "Rock Collecting", hint: "Rocks" },
    { word: "Stand-up", hint: "Comedy" },
    { word: "Puzzling", hint: "Pieces" }
  ],
  "Objects": [
    { word: "Umbrella", hint: "Rain" },
    { word: "Lantern", hint: "Light" },
    { word: "Compass", hint: "Direction" },
    { word: "Binoculars", hint: "Look" },
    { word: "Hammock", hint: "Sleep" },
    { word: "Backpack", hint: "Carry" },
    { word: "Candle", hint: "Light" },
    { word: "Funnel", hint: "Pour" },
    { word: "Telescope", hint: "Look" },
    { word: "Whistle", hint: "Loud" },
    { word: "Thermos", hint: "Hot" },
    { word: "Magnifying", hint: "Look" },
    { word: "Suitcase", hint: "Travel" },
    { word: "Barometer", hint: "Weather" },
    { word: "Harmonica", hint: "Music" },
    { word: "Pendulum", hint: "Swing" },
    { word: "Trowel", hint: "Garden" },
    { word: "Tweezers", hint: "Small" },
    { word: "Spigot", hint: "Water" },
    { word: "Flippers", hint: "Water" },
    { word: "Mannequin", hint: "Dummy" },
    { word: "Stethoscope", hint: "Doctor" },
    { word: "Treadmill", hint: "Run" },
    { word: "Metronome", hint: "Music" },
    { word: "Papyrus", hint: "Old" },
    { word: "Megaphone", hint: "Loud" },
    { word: "Pegboard", hint: "Hooks" },
    { word: "Pipette", hint: "Small" },
    { word: "Spatula", hint: "Cooking" },
    { word: "Tongs", hint: "Cooking" },
    { word: "Airplane", hint: "Fly" },
    { word: "Bicycle", hint: "Wheels" },
    { word: "Clock", hint: "Time" },
    { word: "Door", hint: "Open" },
    { word: "Elevator", hint: "Up" },
    { word: "Fax Machine", hint: "Old" },
    { word: "Guitar", hint: "Music" },
    { word: "Helicopter", hint: "Fly" },
    { word: "Iron", hint: "Hot" },
    { word: "Juicer", hint: "Kitchen" },
    { word: "Keyboard", hint: "Type" },
    { word: "Ladder", hint: "Climb" },
    { word: "Microscope", hint: "Small" },
    { word: "Nutcracker", hint: "Crack" },
    { word: "Oven", hint: "Cook" },
    { word: "Piano", hint: "Music" },
    { word: "Queue Sign", hint: "Wait" },
    { word: "Ruler", hint: "Measure" },
    { word: "Screwdriver", hint: "Twist" },
    { word: "Trampoline", hint: "Bounce" }
  ],
  "Nature": [
    { word: "Waterfall", hint: "Water" },
    { word: "Volcano", hint: "Hot" },
    { word: "Glacier", hint: "Cold" },
    { word: "Rainbow", hint: "Sky" },
    { word: "Thunder", hint: "Loud" },
    { word: "Mushroom", hint: "Forest" },
    { word: "Coral", hint: "Sea" },
    { word: "Fossil", hint: "Old" },
    { word: "Lagoon", hint: "Water" },
    { word: "Blizzard", hint: "Cold" },
    { word: "Meadow", hint: "Green" },
    { word: "Monsoon", hint: "Rain" },
    { word: "Tornado", hint: "Wind" },
    { word: "Canyon", hint: "Deep" },
    { word: "Eclipse", hint: "Sky" },
    { word: "Geyser", hint: "Hot" },
    { word: "Oasis", hint: "Water" },
    { word: "Aurora", hint: "Sky" },
    { word: "Savanna", hint: "Grass" },
    { word: "Typhoon", hint: "Wind" },
    { word: "Mangrove", hint: "Wet" },
    { word: "Tundra", hint: "Cold" },
    { word: "Magma", hint: "Hot" },
    { word: "Dewdrop", hint: "Morning" },
    { word: "Summit", hint: "High" },
    { word: "Cactus", hint: "Dry" },
    { word: "Taiga", hint: "Cold" },
    { word: "Delta", hint: "Water" },
    { word: "Grove", hint: "Trees" },
    { word: "Prairie", hint: "Grass" },
    { word: "Antarctica", hint: "Cold" },
    { word: "Beach", hint: "Sand" },
    { word: "Cloud", hint: "Sky" },
    { word: "Desert", hint: "Dry" },
    { word: "Earthquake", hint: "Shake" },
    { word: "Fog", hint: "Misty" },
    { word: "Grassland", hint: "Green" },
    { word: "Hail", hint: "Ice" },
    { word: "Island", hint: "Water" },
    { word: "Jungle", hint: "Trees" },
    { word: "Kettle Lake", hint: "Water" },
    { word: "Lava", hint: "Hot" },
    { word: "Moon", hint: "Night" },
    { word: "Northern Lights", hint: "Sky" },
    { word: "Ocean", hint: "Water" },
    { word: "Polar Bear", hint: "Animal" },
    { word: "Quartz", hint: "Rock" },
    { word: "River", hint: "Water" },
    { word: "Snow", hint: "White" },
    { word: "Tropic", hint: "Warm" }
  ],
  "Famous People": [
    { word: "Einstein", hint: "Scientist" },
    { word: "Mozart", hint: "Musician" },
    { word: "Cleopatra", hint: "Queen" },
    { word: "Picasso", hint: "Artist" },
    { word: "Shakespeare", hint: "Writer" },
    { word: "Da Vinci", hint: "Artist" },
    { word: "Napoleon", hint: "Emperor" },
    { word: "Frida", hint: "Artist" },
    { word: "Tesla", hint: "Scientist" },
    { word: "Gandhi", hint: "Leader" },
    { word: "Buddha", hint: "Teacher" },
    { word: "Nefertiti", hint: "Queen" },
    { word: "Marco Polo", hint: "Traveler" },
    { word: "Caesar", hint: "Emperor" },
    { word: "Newton", hint: "Scientist" },
    { word: "Darwin", hint: "Scientist" },
    { word: "Amelia", hint: "Pilot" },
    { word: "Gutenberg", hint: "Inventor" },
    { word: "Tutankhamun", hint: "King" },
    { word: "Socrates", hint: "Teacher" },
    { word: "Abraham Lincoln", hint: "President" },
    { word: "Beyonce", hint: "Singer" },
    { word: "Charlie Chaplin", hint: "Comedy" },
    { word: "Dali", hint: "Artist" },
    { word: "Elvis", hint: "Singer" },
    { word: "Franklin", hint: "Inventor" },
    { word: "Houdini", hint: "Magic" },
    { word: "Isaac Newton", hint: "Science" },
    { word: "Julius Caesar", hint: "Emperor" },
    { word: "Kofi Annan", hint: "Diplomat" },
    { word: "Leonardo DiCaprio", hint: "Actor" },
    { word: "Marie Curie", hint: "Scientist" },
    { word: "Nikola Tesla", hint: "Inventor" },
    { word: "Oprah", hint: "Host" },
    { word: "Pele", hint: "Football" },
    { word: "Queen Elizabeth", hint: "Queen" },
    { word: "Rosa Parks", hint: "Activist" },
    { word: "Steve Jobs", hint: "Tech" },
    { word: "Tina Turner", hint: "Singer" },
    { word: "Usain Bolt", hint: "Runner" },
    { word: "Vincent van Gogh", hint: "Artist" },
    { word: "Winston Churchill", hint: "Leader" },
    { word: "Xavi", hint: "Football" },
    { word: "Yoda", hint: "Fictional" },
    { word: "Zendaya", hint: "Actress" },
    { word: "Confucius", hint: "Teacher" },
    { word: "Alan Turing", hint: "Computer" },
    { word: "Bill Gates", hint: "Tech" },
    { word: "Coco Chanel", hint: "Fashion" },
    { word: "David Beckham", hint: "Football" }
  ]
};

export const RECENT_LIMIT = 10;

export function getRandomWord(
  category: string,
  exclude: string[] = []
): { word: string; hint: string } {
  const list = category === 'mixed'
    ? Object.values(categories).flat()
    : categories[category] || Object.values(categories).flat();
  const excluded = new Set(exclude.map((w) => w.toLowerCase()));
  const pool = list.filter((w) => !excluded.has(w.word.toLowerCase()));
  return pool.length
    ? pool[Math.floor(Math.random() * pool.length)]
    : list[Math.floor(Math.random() * list.length)];
}
