export const categories = {
  Animals: [
    { word: 'Elephant', hint: 'Big trunk' },
    { word: 'Giraffe', hint: 'Long neck' },
    { word: 'Penguin', hint: 'Waddling tux' },
    { word: 'Dolphin', hint: 'Playful flipper' },
    { word: 'Kangaroo', hint: 'Pocket hopper' },
    { word: 'Octopus', hint: 'Eight arms' },
    { word: 'Flamingo', hint: 'Pink wader' },
    { word: 'Cheetah', hint: 'Fastest runner' },
    { word: 'Panda', hint: 'Bamboo bear' },
    { word: 'Chameleon', hint: 'Color changer' },
    { word: 'Peacock', hint: 'Fancy tail' },
    { word: 'Hamster', hint: 'Pocket pet' },
    { word: 'Jaguar', hint: 'Spotted cat' },
    { word: 'Koala', hint: 'Eucalyptus bear' },
    { word: 'Lobster', hint: 'Clawed red' },
    { word: 'Chimpanzee', hint: 'Clever ape' },
    { word: 'Walrus', hint: 'Tusked swimmer' },
    { word: 'Parrot', hint: 'Talking bird' },
    { word: 'Scorpion', hint: 'Stinging tail' },
    { word: 'Toucan', hint: 'Big beak' },
    { word: 'Hedgehog', hint: 'Spiky ball' },
    { word: 'Platypus', hint: 'Duck bill' },
    { word: 'Raccoon', hint: 'Masked bandit' },
    { word: 'Seahorse', hint: 'Ocean horse' },
    { word: 'Sloth', hint: 'Slow climber' },
    { word: 'Meerkat', hint: 'Standing guard' },
    { word: 'Narwhal', hint: 'Unicorn whale' },
    { word: 'Otter', hint: 'Rock juggler' },
    { word: 'Puffin', hint: 'Colorful beak' },
    { word: 'Armadillo', hint: 'Shelled digger' }
  ],
  'Food & Drink': [
    { word: 'Pizza', hint: 'Cheesy round' },
    { word: 'Sushi', hint: 'Rice roll' },
    { word: 'Tacos', hint: 'Wrapped crunch' },
    { word: 'Pasta', hint: 'Italian noodles' },
    { word: 'Burger', hint: 'Bun patty' },
    { word: 'Croissant', hint: 'Flaky crescent' },
    { word: 'Paella', hint: 'Spanish rice' },
    { word: 'Ramen', hint: 'Soup noodles' },
    { word: 'Dim Sum', hint: 'Dumpling baskets' },
    { word: 'Falafel', hint: 'Fried chickpea' },
    { word: 'Brownie', hint: 'Chocolate square' },
    { word: 'Mango', hint: 'Tropical fruit' },
    { word: 'Avocado', hint: 'Green spread' },
    { word: 'Bacon', hint: 'Crispy strips' },
    { word: 'Cinnamon', hint: 'Warm spice' },
    { word: 'Wasabi', hint: 'Green heat' },
    { word: 'Saffron', hint: 'Golden spice' },
    { word: 'Kimchi', hint: 'Spicy cabbage' },
    { word: 'Mozzarella', hint: 'Melting cheese' },
    { word: 'Gumbo', hint: 'Cajun stew' },
    { word: 'Churro', hint: 'Sugar sticks' },
    { word: 'Baguette', hint: 'Long bread' },
    { word: 'Cannoli', hint: 'Sicilian pastry' },
    { word: 'Hummus', hint: 'Chickpea dip' },
    { word: 'Matcha', hint: 'Green tea' },
    { word: 'Lasagna', hint: 'Layered bake' },
    { word: 'Bagel', hint: 'Ring bread' },
    { word: 'Kebab', hint: 'Skewered meat' },
    { word: 'Cupcake', hint: 'Iced mini' },
    { word: 'Pancake', hint: 'Fluffy stack' }
  ],
  Countries: [
    { word: 'Japan', hint: 'Rising sun' },
    { word: 'Brazil', hint: 'Samba land' },
    { word: 'Iceland', hint: 'Fire ice' },
    { word: 'Egypt', hint: 'Nile pyramids' },
    { word: 'Thailand', hint: 'Land of smiles' },
    { word: 'Peru', hint: 'Machu Picchu' },
    { word: 'Norway', hint: 'Fjord north' },
    { word: 'Kenya', hint: 'Safari plains' },
    { word: 'Cuba', hint: 'Cigar island' },
    { word: 'Nepal', hint: 'Everest home' },
    { word: 'Vietnam', hint: 'Pho country' },
    { word: 'Greece', hint: 'Olympus islands' },
    { word: 'Morocco', hint: 'Sahara spice' },
    { word: 'Chile', hint: 'Long skinny' },
    { word: 'Finland', hint: 'Sauna lakes' },
    { word: 'Indonesia', hint: 'Island chain' },
    { word: 'Jamaica', hint: 'Reggae island' },
    { word: 'Madagascar', hint: 'Lemur island' },
    { word: 'Mongolia', hint: 'Nomad steppe' },
    { word: 'Portugal', hint: 'Custard tarts' },
    { word: 'Scotland', hint: 'Loch bagpipes' },
    { word: 'Sri Lanka', hint: 'Tea pearls' },
    { word: 'Tanzania', hint: 'Kilimanjaro land' },
    { word: 'Uruguay', hint: 'Mate drink' },
    { word: 'Cambodia', hint: 'Angkor temples' },
    { word: 'Ethiopia', hint: 'Coffee origin' },
    { word: 'Hungary', hint: 'Paprika goulash' },
    { word: 'Ireland', hint: 'Emerald clovers' },
    { word: 'Myanmar', hint: 'Golden pagodas' },
    { word: 'Sweden', hint: 'Northern lights' }
  ],
  Movies: [
    { word: 'Titanic', hint: 'Sinking ship' },
    { word: 'Avatar', hint: 'Blue aliens' },
    { word: 'Jaws', hint: 'Shark thriller' },
    { word: 'Frozen', hint: 'Elsa ice' },
    { word: 'Gladiator', hint: 'Roman arena' },
    { word: 'Inception', hint: 'Dream heist' },
    { word: 'Casablanca', hint: "Rick's café" },
    { word: 'Rocky', hint: 'Underdog boxer' },
    { word: 'Alien', hint: 'Space horror' },
    { word: 'Braveheart', hint: 'Scottish freedom' },
    { word: 'Amelie', hint: 'Montmartre magic' },
    { word: 'Vertigo', hint: 'Hitchcock heights' },
    { word: 'Jumanji', hint: 'Board game' },
    { word: 'Ratatouille', hint: 'Remy cooking' },
    { word: 'Shrek', hint: 'Green ogre' },
    { word: 'Memento', hint: 'Reverse memory' },
    { word: 'Coco', hint: 'Day of dead' },
    { word: 'Fargo', hint: 'Minnesota crime' },
    { word: 'Scream', hint: 'Ghostface killer' },
    { word: 'Twister', hint: 'Storm chasers' },
    { word: 'Bambi', hint: 'Baby deer' },
    { word: 'Gremlins', hint: 'Feed midnight' },
    { word: 'Chocolat', hint: 'Charming chocolate' },
    { word: 'Babe', hint: 'Talking pig' },
    { word: 'Signs', hint: 'Corn circles' },
    { word: 'Prestige', hint: 'Magic duel' },
    { word: 'Crash', hint: 'LA lives' },
    { word: 'Slumdog', hint: 'Mumbai millionaire' },
    { word: 'Up', hint: 'House balloons' },
    { word: 'WALL-E', hint: 'Trash robot' }
  ],
  Sports: [
    { word: 'Soccer', hint: "World's game" },
    { word: 'Basketball', hint: 'Hoop dunk' },
    { word: 'Tennis', hint: 'Grand slams' },
    { word: 'Boxing', hint: 'Ring fists' },
    { word: 'Surfing', hint: 'Wave riding' },
    { word: 'Cricket', hint: 'Batsmen bowlers' },
    { word: 'Fencing', hint: 'Blade duel' },
    { word: 'Curling', hint: 'Stone sweeping' },
    { word: 'Karate', hint: 'Belt martial' },
    { word: 'Rugby', hint: 'Oval ball' },
    { word: 'Badminton', hint: 'Shuttlecock smash' },
    { word: 'Skiing', hint: 'Snow slopes' },
    { word: 'Volleyball', hint: 'Net spike' },
    { word: 'Archery', hint: 'Bow arrows' },
    { word: 'Cycling', hint: 'Pedal racing' },
    { word: 'Snooker', hint: 'Pool table' },
    { word: 'Judo', hint: 'Throw sport' },
    { word: 'Lacrosse', hint: 'Net stick' },
    { word: 'Rowing', hint: 'Oar crew' },
    { word: 'Dodgeball', hint: 'Duck balls' },
    { word: 'Triathlon', hint: 'Swim bike' },
    { word: 'Polo', hint: 'Horse mallet' },
    { word: 'Bowling', hint: 'Strike pins' },
    { word: 'Parkour', hint: 'Urban leap' },
    { word: 'Snowboarding', hint: 'Board powder' },
    { word: 'Taekwondo', hint: 'Kicking art' },
    { word: 'Handball', hint: 'Goalkeeper sport' },
    { word: 'Mountain', hint: 'Peak climbing' },
    { word: 'Kayaking', hint: 'Paddle rapids' },
    { word: 'Bouldering', hint: 'Short climb' }
  ],
  Hobbies: [
    { word: 'Gardening', hint: 'Growing plants' },
    { word: 'Knitting', hint: 'Yarn needles' },
    { word: 'Origami', hint: 'Paper folding' },
    { word: 'Calligraphy', hint: 'Fancy writing' },
    { word: 'Pottery', hint: 'Clay spinning' },
    { word: 'Geocaching', hint: 'GPS treasure' },
    { word: 'Scrapbook', hint: 'Photo memory' },
    { word: 'Birdwatch', hint: 'Feather spotting' },
    { word: 'Astronomy', hint: 'Stargazing hobby' },
    { word: 'Woodwork', hint: 'Carpenter hobby' },
    { word: 'Sudoku', hint: 'Number grid' },
    { word: 'Chess', hint: 'Board strategy' },
    { word: 'Photography', hint: 'Camera shots' },
    { word: 'Baking', hint: 'Oven sweets' },
    { word: 'Camping', hint: 'Tent outdoors' },
    { word: 'Fishing', hint: 'Hook line' },
    { word: 'Yoga', hint: 'Stretching calm' },
    { word: 'Brewing', hint: 'Homemade beer' },
    { word: 'Sewing', hint: 'Needle thread' },
    { word: 'Drawing', hint: 'Pencil sketch' },
    { word: 'Meditation', hint: 'Mindful silence' },
    { word: 'Tattoo', hint: 'Ink design' },
    { word: 'Magic', hint: 'Card tricks' },
    { word: 'Karaoke', hint: 'Singalong mic' },
    { word: 'Collecting', hint: 'Stamp hobby' },
    { word: 'Hiking', hint: 'Trail walking' },
    { word: 'Painting', hint: 'Canvas brush' },
    { word: 'Dancing', hint: 'Rhythm moves' },
    { word: 'Running', hint: 'Cardio jog' },
    { word: 'Reading', hint: 'Book pages' }
  ],
  Objects: [
    { word: 'Umbrella', hint: 'Rain canopy' },
    { word: 'Lantern', hint: 'Glowing light' },
    { word: 'Compass', hint: 'Direction needle' },
    { word: 'Binoculars', hint: 'Two lenses' },
    { word: 'Hammock', hint: 'Hanging rest' },
    { word: 'Backpack', hint: 'Travel bag' },
    { word: 'Candle', hint: 'Wax flame' },
    { word: 'Funnel', hint: 'Pouring cone' },
    { word: 'Telescope', hint: 'Star scope' },
    { word: 'Whistle', hint: 'Loud blow' },
    { word: 'Thermos', hint: 'Hot flask' },
    { word: 'Magnifying', hint: 'Zoom lens' },
    { word: 'Suitcase', hint: 'Travel luggage' },
    { word: 'Barometer', hint: 'Pressure gauge' },
    { word: 'Harmonica', hint: 'Mouth organ' },
    { word: 'Pendulum', hint: 'Swing weight' },
    { word: 'Trowel', hint: 'Garden tool' },
    { word: 'Tweezers', hint: 'Pinch grip' },
    { word: 'Spigot', hint: 'Water tap' },
    { word: 'Flippers', hint: 'Swim fins' },
    { word: 'Mannequin', hint: 'Store dummy' },
    { word: 'Stethoscope', hint: 'Heart listen' },
    { word: 'Treadmill', hint: 'Running machine' },
    { word: 'Metronome', hint: 'Beat timer' },
    { word: 'Papyrus', hint: 'Ancient paper' },
    { word: 'Megaphone', hint: 'Loudspeaker horn' },
    { word: 'Pegboard', hint: 'Hole board' },
    { word: 'Pipette', hint: 'Drop tube' },
    { word: 'Spatula', hint: 'Flip tool' },
    { word: 'Tongs', hint: 'Kitchen pinchers' }
  ],
  Nature: [
    { word: 'Waterfall', hint: 'Falling water' },
    { word: 'Volcano', hint: 'Erupting lava' },
    { word: 'Glacier', hint: 'Frozen river' },
    { word: 'Rainbow', hint: 'Color arc' },
    { word: 'Thunder', hint: 'Loud rumble' },
    { word: 'Mushroom', hint: 'Forest cap' },
    { word: 'Coral', hint: 'Reef builder' },
    { word: 'Fossil', hint: 'Old bones' },
    { word: 'Lagoon', hint: 'Shallow water' },
    { word: 'Blizzard', hint: 'Snowstorm fury' },
    { word: 'Meadow', hint: 'Flower field' },
    { word: 'Monsoon', hint: 'Rainy season' },
    { word: 'Tornado', hint: 'Twister winds' },
    { word: 'Canyon', hint: 'Deep gorge' },
    { word: 'Eclipse', hint: 'Sun shadow' },
    { word: 'Geyser', hint: 'Hot spout' },
    { word: 'Oasis', hint: 'Desert pool' },
    { word: 'Aurora', hint: 'Sky lights' },
    { word: 'Savanna', hint: 'Grassy plains' },
    { word: 'Typhoon', hint: 'Storm cyclone' },
    { word: 'Mangrove', hint: 'Swamp trees' },
    { word: 'Tundra', hint: 'Frozen plain' },
    { word: 'Magma', hint: 'Molten rock' },
    { word: 'Dewdrop', hint: 'Morning droplets' },
    { word: 'Summit', hint: 'Mountain top' },
    { word: 'Cactus', hint: 'Desert plant' },
    { word: 'Taiga', hint: 'Boreal forest' },
    { word: 'Delta', hint: 'River mouth' },
    { word: 'Grove', hint: 'Tree cluster' },
    { word: 'Prairie', hint: 'Open grassland' }
  ],
  'Famous People': [
    { word: 'Einstein', hint: 'Genius physicist' },
    { word: 'Mozart', hint: 'Child prodigy' },
    { word: 'Cleopatra', hint: 'Nile queen' },
    { word: 'Picasso', hint: 'Cubist painter' },
    { word: 'Shakespeare', hint: 'Bard plays' },
    { word: 'Da Vinci', hint: 'Mona Lisa' },
    { word: 'Napoleon', hint: 'French emperor' },
    { word: 'Frida', hint: 'Brow artist' },
    { word: 'Tesla', hint: 'Current inventor' },
    { word: 'Gandhi', hint: 'Peace march' },
    { word: 'Buddha', hint: 'Enlightened one' },
    { word: 'Nefertiti', hint: 'Egyptian queen' },
    { word: 'Marco Polo', hint: 'Silk explorer' },
    { word: 'Caesar', hint: 'Roman dictator' },
    { word: 'Newton', hint: 'Apple gravity' },
    { word: 'Darwin', hint: 'Evolution naturalist' },
    { word: 'Amelia', hint: 'Aviator pioneer' },
    { word: 'Gutenberg', hint: 'Printing press' },
    { word: 'Tutankhamun', hint: 'Boy king' },
    { word: 'Socrates', hint: 'Greek philosopher' }
  ]
}

export function getRandomWord(category) {
  const list = category === 'mixed'
    ? Object.values(categories).flat()
    : categories[category] || Object.values(categories).flat()
  return list[Math.floor(Math.random() * list.length)]
}
