export const categories = {
  "Animals": [
    { word: "Elephant", hint: "Wild" },
    { word: "Giraffe", hint: "Tall" },
    { word: "Penguin", hint: "Cold" },
    { word: "Dolphin", hint: "Ocean" },
    { word: "Kangaroo", hint: "Hops" },
    { word: "Octopus", hint: "Underwater" },
    { word: "Flamingo", hint: "Colorful" },
    { word: "Cheetah", hint: "Fast" },
    { word: "Panda", hint: "Forest" },
    { word: "Chameleon", hint: "Colorful" },
    { word: "Peacock", hint: "Colorful" },
    { word: "Hamster", hint: "Small" },
    { word: "Jaguar", hint: "Wild" },
    { word: "Koala", hint: "Trees" },
    { word: "Lobster", hint: "Ocean" },
    { word: "Chimpanzee", hint: "Smart" },
    { word: "Walrus", hint: "Cold" },
    { word: "Parrot", hint: "Talks" },
    { word: "Scorpion", hint: "Desert" },
    { word: "Toucan", hint: "Tropical" },
    { word: "Hedgehog", hint: "Spikes" },
    { word: "Platypus", hint: "Unusual" },
    { word: "Raccoon", hint: "Night" },
    { word: "Seahorse", hint: "Ocean" },
    { word: "Sloth", hint: "Slow" },
    { word: "Meerkat", hint: "Desert" },
    { word: "Narwhal", hint: "Arctic" },
    { word: "Otter", hint: "River" },
    { word: "Puffin", hint: "Sea" },
    { word: "Armadillo", hint: "Hard" },
    { word: "Buffalo", hint: "Horns" },
    { word: "Camel", hint: "Desert" },
    { word: "Dragonfly", hint: "Wings" },
    { word: "Eagle", hint: "Wings" },
    { word: "Ferret", hint: "Small" },
    { word: "Gecko", hint: "Scales" },
    { word: "Heron", hint: "Wings" },
    { word: "Iguana", hint: "Desert" },
    { word: "Lemur", hint: "Islands" },
    { word: "Moose", hint: "Wild" },
    { word: "Newt", hint: "Water" },
    { word: "Ostrich", hint: "Fast" },
    { word: "Pelican", hint: "Wings" },
    { word: "Quail", hint: "Small" },
    { word: "Rhinoceros", hint: "Horns" },
    { word: "Starfish", hint: "Slow" },
    { word: "Tiger", hint: "Wild" },
    { word: "Vulture", hint: "Wings" },
    { word: "Yak", hint: "Hairy" },
    { word: "Wolverine", hint: "Wild" },
    { word: "Alpaca", hint: "Hairy" },
    { word: "Antelope", hint: "Fast" },
    { word: "Axolotl", hint: "Water" },
    { word: "Baboon", hint: "Smart" },
    { word: "Badger", hint: "Forest" },
    { word: "Beaver", hint: "River" },
    { word: "Bison", hint: "Wild" },
    { word: "Boar", hint: "Forest" },
    { word: "Butterfly", hint: "Colorful" },
    { word: "Capybara", hint: "River" },
    { word: "Cat", hint: "Small" },
    { word: "Chicken", hint: "Farm" },
    { word: "Cobra", hint: "Scales" },
    { word: "Crab", hint: "Ocean" },
    { word: "Crocodile", hint: "Water" },
    { word: "Deer", hint: "Forest" },
    { word: "Duck", hint: "Water" },
    { word: "Firefly", hint: "Night" },
    { word: "Fox", hint: "Wild" },
    { word: "Frog", hint: "Small" },
    { word: "Goldfish", hint: "Small" },
    { word: "Gorilla", hint: "Smart" },
    { word: "Guinea Pig", hint: "Small" },
    { word: "Hawk", hint: "Wings" },
    { word: "Hippo", hint: "Big" },
    { word: "Horse", hint: "Fast" },
    { word: "Hyena", hint: "Wild" },
    { word: "Jellyfish", hint: "Water" },
    { word: "Kingfisher", hint: "Wings" },
    { word: "Ladybug", hint: "Small" },
    { word: "Leopard", hint: "Wild" },
    { word: "Lion", hint: "Wild" },
    { word: "Mongoose", hint: "Small" },
    { word: "Monkey", hint: "Smart" },
    { word: "Owl", hint: "Night" },
    { word: "Pig", hint: "Farm" },
    { word: "Rabbit", hint: "Fast" },
    { word: "Reindeer", hint: "Cold" },
    { word: "Salamander", hint: "Water" },
    { word: "Seal", hint: "Ocean" },
    { word: "Skunk", hint: "Forest" },
    { word: "Snake", hint: "Scales" },
    { word: "Spider", hint: "Small" },
    { word: "Swan", hint: "Water" },
    { word: "Turtle", hint: "Slow" },
    { word: "Whale", hint: "Big" },
    { word: "Wolf", hint: "Wild" },
    { word: "Zebra", hint: "Wild" },
    { word: "Anaconda", hint: "Scales" },
    { word: "Caterpillar", hint: "Small" },
  ],
  "Food & Drink": [
    { word: "Pizza", hint: "Cheesy" },
    { word: "Sushi", hint: "Rice" },
    { word: "Tacos", hint: "Folded" },
    { word: "Pasta", hint: "Italian" },
    { word: "Burger", hint: "Fast food" },
    { word: "Croissant", hint: "Breakfast" },
    { word: "Paella", hint: "Spanish" },
    { word: "Ramen", hint: "Soup" },
    { word: "Dim Sum", hint: "Steamed" },
    { word: "Falafel", hint: "Fried" },
    { word: "Brownie", hint: "Sweet" },
    { word: "Mango", hint: "Sweet" },
    { word: "Avocado", hint: "Green" },
    { word: "Bacon", hint: "Breakfast" },
    { word: "Cinnamon", hint: "Spicy" },
    { word: "Wasabi", hint: "Green" },
    { word: "Saffron", hint: "Spicy" },
    { word: "Kimchi", hint: "Spicy" },
    { word: "Mozzarella", hint: "Cheesy" },
    { word: "Gumbo", hint: "Soup" },
    { word: "Churro", hint: "Fried" },
    { word: "Baguette", hint: "Bread" },
    { word: "Cannoli", hint: "Sweet" },
    { word: "Hummus", hint: "Dip" },
    { word: "Matcha", hint: "Green" },
    { word: "Lasagna", hint: "Italian" },
    { word: "Bagel", hint: "Bread" },
    { word: "Kebab", hint: "Grilled" },
    { word: "Cupcake", hint: "Sweet" },
    { word: "Pancake", hint: "Breakfast" },
    { word: "Almond", hint: "Crunchy" },
    { word: "Chili", hint: "Spicy" },
    { word: "Durian", hint: "Tropical" },
    { word: "Eggplant", hint: "Grilled" },
    { word: "Figs", hint: "Fruity" },
    { word: "Ginger", hint: "Spicy" },
    { word: "Honey", hint: "Sweet" },
    { word: "Ice Cream", hint: "Cold" },
    { word: "Jalapeno", hint: "Spicy" },
    { word: "Kiwi", hint: "Green" },
    { word: "Lemon", hint: "Sour" },
    { word: "Nachos", hint: "Cheesy" },
    { word: "Olive", hint: "Salty" },
    { word: "Pineapple", hint: "Tropical" },
    { word: "Quinoa", hint: "Grain" },
    { word: "Raisin", hint: "Dried" },
    { word: "Truffle", hint: "Fancy" },
    { word: "Popcorn", hint: "Crunchy" },
    { word: "Waffles", hint: "Breakfast" },
    { word: "Salsa", hint: "Dip" },
    { word: "Apple", hint: "Fruity" },
    { word: "Banana", hint: "Tropical" },
    { word: "BBQ", hint: "Grilled" },
    { word: "Butter", hint: "Creamy" },
    { word: "Cake", hint: "Sweet" },
    { word: "Cheese", hint: "Creamy" },
    { word: "Chocolate", hint: "Sweet" },
    { word: "Coffee", hint: "Hot" },
    { word: "Crepe", hint: "Folded" },
    { word: "Curry", hint: "Spicy" },
    { word: "Donut", hint: "Sweet" },
    { word: "Dumpling", hint: "Steamed" },
    { word: "Gelato", hint: "Cold" },
    { word: "Granola", hint: "Crunchy" },
    { word: "Guacamole", hint: "Dip" },
    { word: "Hot Dog", hint: "Fast food" },
    { word: "Ketchup", hint: "Sauce" },
    { word: "Marshmallow", hint: "Soft" },
    { word: "Muffin", hint: "Bread" },
    { word: "Noodles", hint: "Soup" },
    { word: "Omelette", hint: "Breakfast" },
    { word: "Papaya", hint: "Tropical" },
    { word: "Pastry", hint: "Sweet" },
    { word: "Peanut", hint: "Crunchy" },
    { word: "Pho", hint: "Soup" },
    { word: "Popsicle", hint: "Cold" },
    { word: "Pretzel", hint: "Salty" },
    { word: "Pudding", hint: "Creamy" },
    { word: "Ravioli", hint: "Folded" },
    { word: "Rice", hint: "Grain" },
    { word: "Salad", hint: "Healthy" },
    { word: "Sandwich", hint: "Fast food" },
    { word: "Sausage", hint: "Grilled" },
    { word: "Smoothie", hint: "Cold" },
    { word: "Soda", hint: "Sweet" },
    { word: "Steak", hint: "Grilled" },
    { word: "Stew", hint: "Soup" },
    { word: "Strawberry", hint: "Fruity" },
    { word: "Tofu", hint: "Soft" },
    { word: "Toast", hint: "Bread" },
    { word: "Watermelon", hint: "Fruity" },
    { word: "Wine", hint: "Fancy" },
    { word: "Yoghurt", hint: "Creamy" },
    { word: "Zucchini", hint: "Green" },
    { word: "Blueberry", hint: "Fruity" },
    { word: "Cereal", hint: "Breakfast" },
    { word: "Cola", hint: "Sweet" },
    { word: "Empanada", hint: "Folded" },
    { word: "Focaccia", hint: "Bread" },
    { word: "Fondue", hint: "Cheesy" },
  ],
  "Countries": [
    { word: "Japan", hint: "Islands" },
    { word: "Brazil", hint: "Warm" },
    { word: "Iceland", hint: "Cold" },
    { word: "Egypt", hint: "Desert" },
    { word: "Thailand", hint: "Hot" },
    { word: "Peru", hint: "Mountains" },
    { word: "Norway", hint: "Cold" },
    { word: "Kenya", hint: "Warm" },
    { word: "Cuba", hint: "Islands" },
    { word: "Nepal", hint: "Mountains" },
    { word: "Vietnam", hint: "Hot" },
    { word: "Greece", hint: "Islands" },
    { word: "Morocco", hint: "Desert" },
    { word: "Chile", hint: "Long" },
    { word: "Finland", hint: "Cold" },
    { word: "Indonesia", hint: "Islands" },
    { word: "Jamaica", hint: "Islands" },
    { word: "Madagascar", hint: "Islands" },
    { word: "Mongolia", hint: "Cold" },
    { word: "Portugal", hint: "Coast" },
    { word: "Scotland", hint: "Cold" },
    { word: "Sri Lanka", hint: "Islands" },
    { word: "Tanzania", hint: "Warm" },
    { word: "Uruguay", hint: "Grasslands" },
    { word: "Cambodia", hint: "Hot" },
    { word: "Ethiopia", hint: "Dry" },
    { word: "Hungary", hint: "Landlocked" },
    { word: "Ireland", hint: "Islands" },
    { word: "Myanmar", hint: "Hot" },
    { word: "Sweden", hint: "Cold" },
    { word: "Argentina", hint: "Warm" },
    { word: "Belgium", hint: "Small" },
    { word: "Canada", hint: "Cold" },
    { word: "Denmark", hint: "Small" },
    { word: "Ecuador", hint: "Warm" },
    { word: "France", hint: "Coast" },
    { word: "Georgia", hint: "Mountains" },
    { word: "Haiti", hint: "Islands" },
    { word: "India", hint: "Hot" },
    { word: "Jordan", hint: "Desert" },
    { word: "Kuwait", hint: "Desert" },
    { word: "Laos", hint: "Landlocked" },
    { word: "Mexico", hint: "Spicy" },
    { word: "Nigeria", hint: "Warm" },
    { word: "Oman", hint: "Desert" },
    { word: "Poland", hint: "Cold" },
    { word: "Qatar", hint: "Desert" },
    { word: "Russia", hint: "Cold" },
    { word: "Turkey", hint: "Coast" },
    { word: "Venezuela", hint: "Warm" },
    { word: "Afghanistan", hint: "Mountains" },
    { word: "Albania", hint: "Coast" },
    { word: "Algeria", hint: "Desert" },
    { word: "Australia", hint: "Islands" },
    { word: "Austria", hint: "Mountains" },
    { word: "Bahamas", hint: "Islands" },
    { word: "Bangladesh", hint: "Hot" },
    { word: "Barbados", hint: "Islands" },
    { word: "Bolivia", hint: "Mountains" },
    { word: "Botswana", hint: "Grasslands" },
    { word: "Bulgaria", hint: "Coast" },
    { word: "Cameroon", hint: "Warm" },
    { word: "Colombia", hint: "Warm" },
    { word: "Costa Rica", hint: "Tropical" },
    { word: "Croatia", hint: "Coast" },
    { word: "Cyprus", hint: "Islands" },
    { word: "Dominican Republic", hint: "Islands" },
    { word: "El Salvador", hint: "Small" },
    { word: "Estonia", hint: "Cold" },
    { word: "Fiji", hint: "Islands" },
    { word: "Ghana", hint: "Warm" },
    { word: "Guatemala", hint: "Tropical" },
    { word: "Honduras", hint: "Tropical" },
    { word: "Kazakhstan", hint: "Cold" },
    { word: "Latvia", hint: "Cold" },
    { word: "Lebanon", hint: "Coast" },
    { word: "Lithuania", hint: "Cold" },
    { word: "Luxembourg", hint: "Small" },
    { word: "Malaysia", hint: "Hot" },
    { word: "Maldives", hint: "Islands" },
    { word: "Malta", hint: "Islands" },
    { word: "Moldova", hint: "Landlocked" },
    { word: "Namibia", hint: "Desert" },
    { word: "Netherlands", hint: "Cold" },
    { word: "Pakistan", hint: "Mountains" },
    { word: "Panama", hint: "Tropical" },
    { word: "Paraguay", hint: "Grasslands" },
    { word: "Philippines", hint: "Islands" },
    { word: "Romania", hint: "Cold" },
    { word: "Rwanda", hint: "Tropical" },
    { word: "Senegal", hint: "Warm" },
    { word: "Singapore", hint: "Small" },
    { word: "Slovakia", hint: "Landlocked" },
    { word: "Slovenia", hint: "Mountains" },
    { word: "South Africa", hint: "Warm" },
    { word: "South Korea", hint: "Cold" },
    { word: "Spain", hint: "Coast" },
    { word: "Switzerland", hint: "Mountains" },
    { word: "Uganda", hint: "Tropical" },
    { word: "Zambia", hint: "Warm" },
  ],
  "Movies": [
    { word: "Titanic", hint: "Romance" },
    { word: "Avatar", hint: "Sci-fi" },
    { word: "Jaws", hint: "Ocean" },
    { word: "Frozen", hint: "Animation" },
    { word: "Gladiator", hint: "Action" },
    { word: "Inception", hint: "Sci-fi" },
    { word: "Casablanca", hint: "Classic" },
    { word: "Rocky", hint: "Sports" },
    { word: "Alien", hint: "Sci-fi" },
    { word: "Braveheart", hint: "Action" },
    { word: "Amelie", hint: "Romance" },
    { word: "Vertigo", hint: "Classic" },
    { word: "Jumanji", hint: "Adventure" },
    { word: "Ratatouille", hint: "Animation" },
    { word: "Shrek", hint: "Animation" },
    { word: "Memento", hint: "Thriller" },
    { word: "Coco", hint: "Animation" },
    { word: "Fargo", hint: "Crime" },
    { word: "Scream", hint: "Horror" },
    { word: "Twister", hint: "Blockbuster" },
    { word: "Bambi", hint: "Animation" },
    { word: "Gremlins", hint: "Horror" },
    { word: "Chocolat", hint: "Romance" },
    { word: "Babe", hint: "Family" },
    { word: "Signs", hint: "Sci-fi" },
    { word: "Prestige", hint: "Thriller" },
    { word: "Crash", hint: "Drama" },
    { word: "Slumdog", hint: "Drama" },
    { word: "Up", hint: "Animation" },
    { word: "WALL-E", hint: "Animation" },
    { word: "Back to the Future", hint: "Classic" },
    { word: "Citizen Kane", hint: "Classic" },
    { word: "E.T.", hint: "Family" },
    { word: "Forrest Gump", hint: "Classic" },
    { word: "Ghostbusters", hint: "Comedy" },
    { word: "Home Alone", hint: "Family" },
    { word: "Interstellar", hint: "Sci-fi" },
    { word: "Jurassic Park", hint: "Blockbuster" },
    { word: "King Kong", hint: "Blockbuster" },
    { word: "La La Land", hint: "Musical" },
    { word: "Mad Max", hint: "Action" },
    { word: "Notebook", hint: "Romance" },
    { word: "Onward", hint: "Animation" },
    { word: "Pulp Fiction", hint: "Crime" },
    { word: "Soul", hint: "Animation" },
    { word: "X-Men", hint: "Superhero" },
    { word: "Zootopia", hint: "Animation" },
    { word: "Metropolis", hint: "Classic" },
    { word: "Blade Runner", hint: "Sci-fi" },
    { word: "Shutter Island", hint: "Thriller" },
    { word: "The Godfather", hint: "Crime" },
    { word: "Star Wars", hint: "Space" },
    { word: "Harry Potter", hint: "Magic" },
    { word: "The Matrix", hint: "Sci-fi" },
    { word: "Toy Story", hint: "Animation" },
    { word: "Finding Nemo", hint: "Ocean" },
    { word: "The Lion King", hint: "Animation" },
    { word: "Die Hard", hint: "Action" },
    { word: "Shawshank Redemption", hint: "Drama" },
    { word: "Spirited Away", hint: "Animation" },
    { word: "Goodfellas", hint: "Crime" },
    { word: "The Dark Knight", hint: "Superhero" },
    { word: "Fight Club", hint: "Thriller" },
    { word: "Schindler's List", hint: "Drama" },
    { word: "Terminator", hint: "Action" },
    { word: "Independence Day", hint: "Blockbuster" },
    { word: "The Princess Bride", hint: "Adventure" },
    { word: "Indiana Jones", hint: "Adventure" },
    { word: "Grease", hint: "Musical" },
    { word: "The Wizard of Oz", hint: "Classic" },
    { word: "The Shining", hint: "Horror" },
    { word: "Psycho", hint: "Horror" },
    { word: "The Exorcist", hint: "Horror" },
    { word: "The Avengers", hint: "Superhero" },
    { word: "Pirates of the Caribbean", hint: "Adventure" },
    { word: "The Hunger Games", hint: "Blockbuster" },
    { word: "Mean Girls", hint: "Comedy" },
    { word: "Superbad", hint: "Comedy" },
    { word: "Bridesmaids", hint: "Comedy" },
    { word: "Wonder Woman", hint: "Superhero" },
    { word: "Black Panther", hint: "Superhero" },
    { word: "Elf", hint: "Family" },
    { word: "Willy Wonka", hint: "Family" },
    { word: "Groundhog Day", hint: "Classic" },
    { word: "The Breakfast Club", hint: "Classic" },
    { word: "Top Gun", hint: "Action" },
    { word: "Pretty Woman", hint: "Romance" },
    { word: "The Sixth Sense", hint: "Thriller" },
    { word: "Get Out", hint: "Horror" },
    { word: "A Quiet Place", hint: "Horror" },
    { word: "Dune", hint: "Sci-fi" },
    { word: "Barbie", hint: "Comedy" },
    { word: "Oppenheimer", hint: "Drama" },
    { word: "Halloween", hint: "Horror" },
    { word: "Godzilla", hint: "Blockbuster" },
    { word: "Robocop", hint: "Action" },
    { word: "Chinatown", hint: "Classic" },
    { word: "Casino", hint: "Crime" },
    { word: "Blue Velvet", hint: "Thriller" },
    { word: "Good Will Hunting", hint: "Drama" },
  ],
  "Sports": [
    { word: "Soccer", hint: "Ball" },
    { word: "Basketball", hint: "Ball" },
    { word: "Tennis", hint: "Racket" },
    { word: "Boxing", hint: "Combat" },
    { word: "Surfing", hint: "Water" },
    { word: "Cricket", hint: "Team" },
    { word: "Fencing", hint: "Combat" },
    { word: "Curling", hint: "Ice" },
    { word: "Karate", hint: "Combat" },
    { word: "Rugby", hint: "Team" },
    { word: "Badminton", hint: "Net" },
    { word: "Skiing", hint: "Winter" },
    { word: "Volleyball", hint: "Net" },
    { word: "Archery", hint: "Precision" },
    { word: "Cycling", hint: "Bike" },
    { word: "Snooker", hint: "Table" },
    { word: "Judo", hint: "Combat" },
    { word: "Lacrosse", hint: "Team" },
    { word: "Rowing", hint: "Water" },
    { word: "Dodgeball", hint: "Ball" },
    { word: "Triathlon", hint: "Endurance" },
    { word: "Polo", hint: "Horses" },
    { word: "Bowling", hint: "Precision" },
    { word: "Parkour", hint: "Agility" },
    { word: "Snowboarding", hint: "Winter" },
    { word: "Taekwondo", hint: "Combat" },
    { word: "Handball", hint: "Ball" },
    { word: "Mountain", hint: "Climbing" },
    { word: "Kayaking", hint: "Water" },
    { word: "Bouldering", hint: "Climbing" },
    { word: "American Football", hint: "Team" },
    { word: "Baseball", hint: "Ball" },
    { word: "Chess Boxing", hint: "Combat" },
    { word: "Diving", hint: "Water" },
    { word: "Equestrian", hint: "Horses" },
    { word: "Frisbee", hint: "Throw" },
    { word: "Golf", hint: "Precision" },
    { word: "Hockey", hint: "Ice" },
    { word: "Ice Skating", hint: "Ice" },
    { word: "Javelin", hint: "Throw" },
    { word: "Kickboxing", hint: "Combat" },
    { word: "Long Jump", hint: "Jumping" },
    { word: "Marathon", hint: "Running" },
    { word: "Netball", hint: "Team" },
    { word: "Paddleboarding", hint: "Water" },
    { word: "Rock Climbing", hint: "Climbing" },
    { word: "Squash", hint: "Racket" },
    { word: "Table Tennis", hint: "Racket" },
    { word: "Ultimate Frisbee", hint: "Team" },
    { word: "Weightlifting", hint: "Strength" },
    { word: "Athletics", hint: "Running" },
    { word: "Biathlon", hint: "Winter" },
    { word: "BMX", hint: "Bike" },
    { word: "Bocce", hint: "Precision" },
    { word: "Canoeing", hint: "Water" },
    { word: "Cheerleading", hint: "Team" },
    { word: "Decathlon", hint: "Endurance" },
    { word: "Darts", hint: "Precision" },
    { word: "Disc Golf", hint: "Throw" },
    { word: "Drag Racing", hint: "Speed" },
    { word: "Esports", hint: "Precision" },
    { word: "Field Hockey", hint: "Team" },
    { word: "Figure Skating", hint: "Ice" },
    { word: "Formula One", hint: "Speed" },
    { word: "Gymnastics", hint: "Agility" },
    { word: "Hammer Throw", hint: "Throw" },
    { word: "Heptathlon", hint: "Endurance" },
    { word: "Horse Racing", hint: "Speed" },
    { word: "Hula Hoop", hint: "Agility" },
    { word: "Ice Climbing", hint: "Climbing" },
    { word: "Inline Skating", hint: "Speed" },
    { word: "Ironman", hint: "Endurance" },
    { word: "Korfball", hint: "Team" },
    { word: "Mixed Martial Arts", hint: "Combat" },
    { word: "Motocross", hint: "Bike" },
    { word: "Orienteering", hint: "Running" },
    { word: "Pentathlon", hint: "Endurance" },
    { word: "Pickleball", hint: "Racket" },
    { word: "Pétanque", hint: "Precision" },
    { word: "Powerlifting", hint: "Strength" },
    { word: "Racquetball", hint: "Racket" },
    { word: "Roller Derby", hint: "Speed" },
    { word: "Sailing", hint: "Water" },
    { word: "Skateboarding", hint: "Agility" },
    { word: "Skeet Shooting", hint: "Precision" },
    { word: "Skydiving", hint: "Extreme" },
    { word: "Sledding", hint: "Winter" },
    { word: "Slopestyle", hint: "Winter" },
    { word: "Snowmobile", hint: "Winter" },
    { word: "Softball", hint: "Ball" },
    { word: "Speed Skating", hint: "Ice" },
    { word: "Sumo", hint: "Combat" },
    { word: "Swimming", hint: "Water" },
    { word: "Trampoline", hint: "Agility" },
    { word: "Water Polo", hint: "Water" },
    { word: "Waterskiing", hint: "Water" },
    { word: "Windsurfing", hint: "Water" },
    { word: "Wrestling", hint: "Combat" },
    { word: "Yoga", hint: "Endurance" },
    { word: "Paragliding", hint: "Extreme" },
  ],
  "Hobbies": [
    { word: "Gardening", hint: "Plants" },
    { word: "Knitting", hint: "Yarn" },
    { word: "Origami", hint: "Paper" },
    { word: "Calligraphy", hint: "Writing" },
    { word: "Pottery", hint: "Clay" },
    { word: "Geocaching", hint: "Exploring" },
    { word: "Scrapbook", hint: "Photos" },
    { word: "Birdwatch", hint: "Birds" },
    { word: "Astronomy", hint: "Stars" },
    { word: "Woodwork", hint: "Wood" },
    { word: "Sudoku", hint: "Numbers" },
    { word: "Chess", hint: "Board" },
    { word: "Photography", hint: "Photos" },
    { word: "Baking", hint: "Kitchen" },
    { word: "Camping", hint: "Outdoors" },
    { word: "Fishing", hint: "Water" },
    { word: "Yoga", hint: "Stretching" },
    { word: "Brewing", hint: "Kitchen" },
    { word: "Sewing", hint: "Fabric" },
    { word: "Drawing", hint: "Art" },
    { word: "Meditation", hint: "Quiet" },
    { word: "Tattoo", hint: "Ink" },
    { word: "Magic", hint: "Tricks" },
    { word: "Karaoke", hint: "Singing" },
    { word: "Collecting", hint: "Things" },
    { word: "Hiking", hint: "Outdoors" },
    { word: "Painting", hint: "Art" },
    { word: "Dancing", hint: "Music" },
    { word: "Running", hint: "Cardio" },
    { word: "Reading", hint: "Books" },
    { word: "Antiquing", hint: "Old" },
    { word: "Bonsai", hint: "Trees" },
    { word: "Coin Collecting", hint: "Coins" },
    { word: "Diorama", hint: "Miniature" },
    { word: "Embroidery", hint: "Needle" },
    { word: "Falconry", hint: "Birds" },
    { word: "Glassblowing", hint: "Hot" },
    { word: "Horseback", hint: "Animals" },
    { word: "Indie Games", hint: "Gaming" },
    { word: "Jewelry Making", hint: "Beads" },
    { word: "Kayaking", hint: "Water" },
    { word: "Lockpicking", hint: "Keys" },
    { word: "Metal Detecting", hint: "Metal" },
    { word: "Model Building", hint: "Miniature" },
    { word: "Needlepoint", hint: "Thread" },
    { word: "Podcasting", hint: "Audio" },
    { word: "Quilting", hint: "Fabric" },
    { word: "Rock Collecting", hint: "Rocks" },
    { word: "Stand-up", hint: "Comedy" },
    { word: "Puzzling", hint: "Pieces" },
    { word: "Acrobatics", hint: "Agility" },
    { word: "Ballet", hint: "Dancing" },
    { word: "Ballroom Dancing", hint: "Dancing" },
    { word: "Beading", hint: "Beads" },
    { word: "Beekeeping", hint: "Outdoors" },
    { word: "Board Games", hint: "Board" },
    { word: "Candle Making", hint: "Handmade" },
    { word: "Card Tricks", hint: "Magic" },
    { word: "Choir", hint: "Singing" },
    { word: "Coding", hint: "Skills" },
    { word: "Cosplay", hint: "Crafts" },
    { word: "Crochet", hint: "Yarn" },
    { word: "Crosswords", hint: "Writing" },
    { word: "Darts", hint: "Precision" },
    { word: "Digital Art", hint: "Art" },
    { word: "DIY", hint: "Handmade" },
    { word: "Drumming", hint: "Music" },
    { word: "Escape Rooms", hint: "Puzzles" },
    { word: "Fashion Design", hint: "Fashion" },
    { word: "Flower Arranging", hint: "Plants" },
    { word: "Genealogy", hint: "History" },
    { word: "Guitar", hint: "Music" },
    { word: "Hula Hooping", hint: "Dancing" },
    { word: "Journaling", hint: "Writing" },
    { word: "Karting", hint: "Speed" },
    { word: "Kite Flying", hint: "Sky" },
    { word: "Language Learning", hint: "Learning" },
    { word: "Legos", hint: "Building" },
    { word: "Letter Writing", hint: "Mail" },
    { word: "Martial Arts", hint: "Fitness" },
    { word: "Music Production", hint: "Audio" },
    { word: "Nail Art", hint: "Hands" },
    { word: "Robotics", hint: "Building" },
    { word: "Sculpting", hint: "Clay" },
    { word: "Singing", hint: "Music" },
    { word: "Soap Making", hint: "Handmade" },
    { word: "Terrarium", hint: "Plants" },
    { word: "Thrifting", hint: "Old" },
    { word: "Travel Blogging", hint: "Writing" },
    { word: "Video Editing", hint: "Computers" },
    { word: "Volunteering", hint: "Helping" },
    { word: "Watching Movies", hint: "Films" },
    { word: "Writing", hint: "Words" },
    { word: "Ziplining", hint: "Adventure" },
    { word: "Bowling", hint: "Precision" },
    { word: "Dominoes", hint: "Board" },
    { word: "Maps", hint: "Exploring" },
    { word: "Model Trains", hint: "Miniature" },
    { word: "Pinball", hint: "Precision" },
    { word: "Aquarium", hint: "Water" },
  ],
  "Objects": [
    { word: "Umbrella", hint: "Rain" },
    { word: "Lantern", hint: "Light" },
    { word: "Compass", hint: "Direction" },
    { word: "Binoculars", hint: "Look" },
    { word: "Hammock", hint: "Sleep" },
    { word: "Backpack", hint: "Carry" },
    { word: "Candle", hint: "Light" },
    { word: "Funnel", hint: "Pour" },
    { word: "Telescope", hint: "Look" },
    { word: "Whistle", hint: "Loud" },
    { word: "Thermos", hint: "Hot" },
    { word: "Magnifying", hint: "Look" },
    { word: "Suitcase", hint: "Travel" },
    { word: "Barometer", hint: "Weather" },
    { word: "Harmonica", hint: "Music" },
    { word: "Pendulum", hint: "Swing" },
    { word: "Trowel", hint: "Garden" },
    { word: "Tweezers", hint: "Small" },
    { word: "Spigot", hint: "Water" },
    { word: "Flippers", hint: "Water" },
    { word: "Mannequin", hint: "Dummy" },
    { word: "Stethoscope", hint: "Doctor" },
    { word: "Treadmill", hint: "Run" },
    { word: "Metronome", hint: "Music" },
    { word: "Papyrus", hint: "Old" },
    { word: "Megaphone", hint: "Loud" },
    { word: "Pegboard", hint: "Hooks" },
    { word: "Pipette", hint: "Small" },
    { word: "Spatula", hint: "Cooking" },
    { word: "Tongs", hint: "Cooking" },
    { word: "Airplane", hint: "Fly" },
    { word: "Bicycle", hint: "Wheels" },
    { word: "Clock", hint: "Time" },
    { word: "Door", hint: "Open" },
    { word: "Elevator", hint: "Up" },
    { word: "Fax Machine", hint: "Old" },
    { word: "Guitar", hint: "Music" },
    { word: "Helicopter", hint: "Fly" },
    { word: "Iron", hint: "Hot" },
    { word: "Juicer", hint: "Kitchen" },
    { word: "Keyboard", hint: "Type" },
    { word: "Ladder", hint: "Climb" },
    { word: "Microscope", hint: "Small" },
    { word: "Nutcracker", hint: "Crack" },
    { word: "Oven", hint: "Cook" },
    { word: "Piano", hint: "Music" },
    { word: "Queue Sign", hint: "Wait" },
    { word: "Ruler", hint: "Measure" },
    { word: "Screwdriver", hint: "Twist" },
    { word: "Trampoline", hint: "Bounce" },
    { word: "Anchor", hint: "Water" },
    { word: "Apron", hint: "Kitchen" },
    { word: "Balloon", hint: "Air" },
    { word: "Battery", hint: "Power" },
    { word: "Beaker", hint: "Glass" },
    { word: "Bellows", hint: "Fire" },
    { word: "Book", hint: "Paper" },
    { word: "Bridge", hint: "Structure" },
    { word: "Calculator", hint: "Numbers" },
    { word: "Camera", hint: "Photos" },
    { word: "Cardboard Box", hint: "Storage" },
    { word: "Catapult", hint: "Throw" },
    { word: "Chessboard", hint: "Wood" },
    { word: "Conch", hint: "Ocean" },
    { word: "Corkscrew", hint: "Kitchen" },
    { word: "Cymbal", hint: "Loud" },
    { word: "Disco Ball", hint: "Shiny" },
    { word: "Doorknob", hint: "Handle" },
    { word: "Drum", hint: "Loud" },
    { word: "Dumbbell", hint: "Weight" },
    { word: "Egg Timer", hint: "Kitchen" },
    { word: "Envelope", hint: "Paper" },
    { word: "Feather", hint: "Soft" },
    { word: "Fire Extinguisher", hint: "Safety" },
    { word: "Flashlight", hint: "Light" },
    { word: "Frying Pan", hint: "Cooking" },
    { word: "Globe", hint: "World" },
    { word: "Hammer", hint: "Tool" },
    { word: "Hanger", hint: "Clothes" },
    { word: "Headphones", hint: "Music" },
    { word: "Hourglass", hint: "Time" },
    { word: "Kite", hint: "Sky" },
    { word: "Laptop", hint: "Electronics" },
    { word: "Lock", hint: "Security" },
    { word: "Magnet", hint: "Metal" },
    { word: "Mailbox", hint: "Mail" },
    { word: "Mirror", hint: "Glass" },
    { word: "Mop", hint: "Cleaning" },
    { word: "Pencil", hint: "Writing" },
    { word: "Phone", hint: "Electronics" },
    { word: "Radio", hint: "Music" },
    { word: "Scissors", hint: "Cut" },
    { word: "Sink", hint: "Water" },
    { word: "Slingshot", hint: "Throw" },
    { word: "Stapler", hint: "Paper" },
    { word: "Thermometer", hint: "Measure" },
    { word: "Typewriter", hint: "Old" },
    { word: "Vase", hint: "Flowers" },
    { word: "Wrench", hint: "Tool" },
    { word: "Bin", hint: "Storage" },
  ],
  "Nature": [
    { word: "Waterfall", hint: "Water" },
    { word: "Volcano", hint: "Hot" },
    { word: "Glacier", hint: "Cold" },
    { word: "Rainbow", hint: "Sky" },
    { word: "Thunder", hint: "Loud" },
    { word: "Mushroom", hint: "Forest" },
    { word: "Coral", hint: "Ocean" },
    { word: "Fossil", hint: "Old" },
    { word: "Lagoon", hint: "Water" },
    { word: "Blizzard", hint: "Cold" },
    { word: "Meadow", hint: "Green" },
    { word: "Monsoon", hint: "Rain" },
    { word: "Tornado", hint: "Wind" },
    { word: "Canyon", hint: "Deep" },
    { word: "Eclipse", hint: "Sky" },
    { word: "Geyser", hint: "Hot" },
    { word: "Oasis", hint: "Water" },
    { word: "Aurora", hint: "Sky" },
    { word: "Savanna", hint: "Grass" },
    { word: "Typhoon", hint: "Wind" },
    { word: "Mangrove", hint: "Wet" },
    { word: "Tundra", hint: "Cold" },
    { word: "Magma", hint: "Hot" },
    { word: "Dewdrop", hint: "Morning" },
    { word: "Summit", hint: "High" },
    { word: "Cactus", hint: "Dry" },
    { word: "Taiga", hint: "Cold" },
    { word: "Delta", hint: "Water" },
    { word: "Grove", hint: "Trees" },
    { word: "Prairie", hint: "Grass" },
    { word: "Antarctica", hint: "Cold" },
    { word: "Beach", hint: "Sand" },
    { word: "Cloud", hint: "Sky" },
    { word: "Desert", hint: "Dry" },
    { word: "Earthquake", hint: "Shake" },
    { word: "Fog", hint: "Misty" },
    { word: "Grassland", hint: "Green" },
    { word: "Hail", hint: "Ice" },
    { word: "Island", hint: "Water" },
    { word: "Jungle", hint: "Trees" },
    { word: "Kettle Lake", hint: "Water" },
    { word: "Lava", hint: "Hot" },
    { word: "Moon", hint: "Night" },
    { word: "Northern Lights", hint: "Sky" },
    { word: "Ocean", hint: "Water" },
    { word: "Polar Bear", hint: "Cold" },
    { word: "Quartz", hint: "Rock" },
    { word: "River", hint: "Water" },
    { word: "Snow", hint: "Cold" },
    { word: "Tropic", hint: "Warm" },
    { word: "Abyss", hint: "Deep" },
    { word: "Acorn", hint: "Trees" },
    { word: "Algae", hint: "Green" },
    { word: "Bamboo", hint: "Tall" },
    { word: "Basalt", hint: "Rock" },
    { word: "Bay", hint: "Water" },
    { word: "Boulder", hint: "Heavy" },
    { word: "Breeze", hint: "Wind" },
    { word: "Caves", hint: "Deep" },
    { word: "Cliffs", hint: "High" },
    { word: "Comet", hint: "Sky" },
    { word: "Craters", hint: "Deep" },
    { word: "Currents", hint: "Water" },
    { word: "Dawn", hint: "Morning" },
    { word: "Driftwood", hint: "Water" },
    { word: "Dunes", hint: "Sand" },
    { word: "Estuary", hint: "Water" },
    { word: "Fjord", hint: "Cold" },
    { word: "Flood", hint: "Water" },
    { word: "Forest", hint: "Trees" },
    { word: "Frost", hint: "Cold" },
    { word: "Galaxy", hint: "Sky" },
    { word: "Geode", hint: "Rock" },
    { word: "Grass", hint: "Green" },
    { word: "Grotto", hint: "Deep" },
    { word: "Hurricane", hint: "Wind" },
    { word: "Iceberg", hint: "Cold" },
    { word: "Meteor", hint: "Sky" },
    { word: "Mist", hint: "Misty" },
    { word: "Mountain", hint: "High" },
    { word: "Nebula", hint: "Sky" },
    { word: "Night Sky", hint: "Sky" },
    { word: "Peninsula", hint: "Water" },
    { word: "Pebble", hint: "Small" },
    { word: "Permafrost", hint: "Cold" },
    { word: "Pinecone", hint: "Trees" },
    { word: "Plateau", hint: "High" },
    { word: "Pond", hint: "Water" },
    { word: "Puddle", hint: "Water" },
    { word: "Quicksand", hint: "Sand" },
    { word: "Reef", hint: "Ocean" },
    { word: "Sand", hint: "Dry" },
    { word: "Shale", hint: "Rock" },
    { word: "Shore", hint: "Water" },
    { word: "Sky", hint: "Blue" },
    { word: "Slope", hint: "High" },
    { word: "Stream", hint: "Water" },
    { word: "Sunrise", hint: "Morning" },
    { word: "Sunset", hint: "Sky" },
    { word: "Twilight", hint: "Sky" },
  ],
  "Famous People": [
    { word: "Einstein", hint: "Scientist" },
    { word: "Mozart", hint: "Musician" },
    { word: "Cleopatra", hint: "Queen" },
    { word: "Picasso", hint: "Artist" },
    { word: "Shakespeare", hint: "Writer" },
    { word: "Da Vinci", hint: "Artist" },
    { word: "Napoleon", hint: "Emperor" },
    { word: "Frida", hint: "Artist" },
    { word: "Tesla", hint: "Inventor" },
    { word: "Gandhi", hint: "Leader" },
    { word: "Buddha", hint: "Teacher" },
    { word: "Nefertiti", hint: "Queen" },
    { word: "Marco Polo", hint: "Traveler" },
    { word: "Caesar", hint: "Emperor" },
    { word: "Newton", hint: "Scientist" },
    { word: "Darwin", hint: "Scientist" },
    { word: "Amelia", hint: "Pilot" },
    { word: "Gutenberg", hint: "Inventor" },
    { word: "Tutankhamun", hint: "King" },
    { word: "Socrates", hint: "Teacher" },
    { word: "Abraham Lincoln", hint: "President" },
    { word: "Beyonce", hint: "Singer" },
    { word: "Charlie Chaplin", hint: "Comedy" },
    { word: "Dali", hint: "Artist" },
    { word: "Elvis", hint: "Singer" },
    { word: "Franklin", hint: "Inventor" },
    { word: "Houdini", hint: "Magic" },
    { word: "Isaac Newton", hint: "Scientist" },
    { word: "Julius Caesar", hint: "Emperor" },
    { word: "Kofi Annan", hint: "Diplomat" },
    { word: "Leonardo DiCaprio", hint: "Actor" },
    { word: "Marie Curie", hint: "Scientist" },
    { word: "Nikola Tesla", hint: "Inventor" },
    { word: "Oprah", hint: "Host" },
    { word: "Pele", hint: "Football" },
    { word: "Queen Elizabeth", hint: "Queen" },
    { word: "Rosa Parks", hint: "Activist" },
    { word: "Steve Jobs", hint: "Tech" },
    { word: "Tina Turner", hint: "Singer" },
    { word: "Usain Bolt", hint: "Runner" },
    { word: "Vincent van Gogh", hint: "Artist" },
    { word: "Winston Churchill", hint: "Leader" },
    { word: "Xavi", hint: "Football" },
    { word: "Yoda", hint: "Fictional" },
    { word: "Zendaya", hint: "Actress" },
    { word: "Confucius", hint: "Teacher" },
    { word: "Alan Turing", hint: "Computer" },
    { word: "Bill Gates", hint: "Tech" },
    { word: "Coco Chanel", hint: "Fashion" },
    { word: "David Beckham", hint: "Football" },
    { word: "Adele", hint: "Singer" },
    { word: "Aristotle", hint: "Teacher" },
    { word: "Audrey Hepburn", hint: "Actress" },
    { word: "Barack Obama", hint: "Leader" },
    { word: "Beethoven", hint: "Musician" },
    { word: "Bowie", hint: "Singer" },
    { word: "Brad Pitt", hint: "Actor" },
    { word: "Bruce Lee", hint: "Actor" },
    { word: "Christopher Columbus", hint: "Explorer" },
    { word: "Cristiano Ronaldo", hint: "Football" },
    { word: "Dwayne Johnson", hint: "Actor" },
    { word: "Ed Sheeran", hint: "Singer" },
    { word: "Elon Musk", hint: "Tech" },
    { word: "Emma Watson", hint: "Actress" },
    { word: "Genghis Khan", hint: "Leader" },
    { word: "George Clooney", hint: "Actor" },
    { word: "Greta Thunberg", hint: "Activist" },
    { word: "Henry Ford", hint: "Inventor" },
    { word: "J.K. Rowling", hint: "Writer" },
    { word: "Jackie Chan", hint: "Actor" },
    { word: "Jane Austen", hint: "Writer" },
    { word: "Jeff Bezos", hint: "Tech" },
    { word: "Jennifer Lopez", hint: "Singer" },
    { word: "John Lennon", hint: "Musician" },
    { word: "Johnny Depp", hint: "Actor" },
    { word: "Julia Roberts", hint: "Actress" },
    { word: "Keanu Reeves", hint: "Actor" },
    { word: "Lady Gaga", hint: "Singer" },
    { word: "Lionel Messi", hint: "Football" },
    { word: "Madonna", hint: "Singer" },
    { word: "Malala", hint: "Activist" },
    { word: "Mark Zuckerberg", hint: "Tech" },
    { word: "Maya Angelou", hint: "Writer" },
    { word: "Michael Jackson", hint: "Singer" },
    { word: "Michael Jordan", hint: "Sports" },
    { word: "Neil Armstrong", hint: "Astronaut" },
    { word: "Oscar Wilde", hint: "Writer" },
    { word: "Paul McCartney", hint: "Musician" },
    { word: "Prince", hint: "Singer" },
    { word: "Rihanna", hint: "Singer" },
    { word: "Robert De Niro", hint: "Actor" },
    { word: "Robin Williams", hint: "Actor" },
    { word: "Roger Federer", hint: "Tennis" },
    { word: "Serena Williams", hint: "Tennis" },
    { word: "Stephen Curry", hint: "Sports" },
    { word: "Stephen Hawking", hint: "Scientist" },
    { word: "Steven Spielberg", hint: "Director" },
    { word: "Taylor Swift", hint: "Singer" },
    { word: "Tiger Woods", hint: "Sports" },
    { word: "Tom Cruise", hint: "Actor" },
  ]
}

export const RECENT_LIMIT = 50

export function getRandomWord(category, exclude = []) {
  const list = category === 'mixed'
    ? Object.values(categories).flat()
    : categories[category] || Object.values(categories).flat()
  const excluded = new Set(exclude.map((w) => w.toLowerCase()))
  const pool = list.filter((w) => !excluded.has(w.word.toLowerCase()))
  return pool.length
    ? pool[Math.floor(Math.random() * pool.length)]
    : list[Math.floor(Math.random() * list.length)]
}
